name: CLI CQU App 的测试、构建、发布

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install deps
        run: |
          python -m pip install poetry
          poetry install
      - name: pytest
        run: |
          poetry run pytest
      - name: build
        run: |
          poetry build
      - name: publish
        run: poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
